# Generated by Django 5.2.9 on 2026-01-12 07:36

import users.models
import uuid
from django.db import migrations, models


def fill_unique_tokens(apps, schema_editor):
    User = apps.get_model('users', 'User')

    existing_tokens = set(
        User.objects
        .exclude(email_confirmation_token='')
        .values_list('email_confirmation_token', flat=True)
    )

    for user in User.objects.all():
        if not user.email_confirmation_token:
            new_token = uuid.uuid4().hex
            while new_token in existing_tokens:
                new_token = uuid.uuid4().hex

            user.email_confirmation_token = new_token
            user.save()
            existing_tokens.add(new_token)

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_telegram_id_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(
                max_length=32,
                editable=False,
                null=True,
                verbose_name="Токен подтверждения"
            ),
        ),
        migrations.RunPython(fill_unique_tokens),
        migrations.AlterField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(
                max_length=32,
                editable=False,
                unique=True,
                verbose_name="Токен подтверждения"
            ),
        ),
    ]
