# Generated by Django 5.2.9 on 2026-01-12 07:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_email_confirmation_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_confirmed",
            field=models.BooleanField(default=False, verbose_name="Email подтверждён"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_confirmation_token",
            field=models.CharField(
                default=users.models.generate_token,
                editable=False,
                max_length=32,
                unique=True,
                verbose_name="Токен подтверждения",
            ),
        ),
    ]
