version: '3.8'

services:
  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "${PORT}:5432"
    networks:
      - app_network

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Gud_habit:/app
      - static_volume:/static
    networks:
      - app_network
    ports:
      - "8080:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Personal_diary.settings
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf
      - ./html:/usr/share/nginx/html
      - static_volume:/usr/share/nginx/html/static
    networks:
      - app_network
    depends_on:
      - django

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
