# Generated by Django 5.2.9 on 2026-01-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Введите название заголовка",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержимое", verbose_name="Содержимое"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото",
                        null=True,
                        upload_to="entries/photo",
                        verbose_name="Фото",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Мой дневник",
                "verbose_name_plural": "Мои дневники",
                "ordering": ["created_at"],
            },
        ),
    ]
