# Generated by Django 5.2.9 on 2026-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entries",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте фото",
                null=True,
                upload_to="entries/photo/",
                verbose_name="Фото",
            ),
        ),
    ]
